FROM python:3.7-alpine3.16

COPY . /app
WORKDIR /app

RUN pip3 install poetry==1.1.14
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

RUN apk update && \
    apk upgrade && \
    apk add \
        shellinabox \
        openssl \
        openssh-client \ 
        curl \
        sudo

ENTRYPOINT [ "~/app/entrypoint.sh" ]
CMD [ "shellinabox" ]